### ISSUE TITLE
 HTTP error 404: "Resource Not Found"

### ISSUE THREAD

**Issue by ghost** [buddydvd/bing-image-search#9]
bing-image-search --key redactedkey --amount 2 apple

HTTP error 404: "Resource Not Found"

**Comment by buddydvd** [comment]
@planetrenox Please retry.

I've updated the Bing Search API end-point from 

    https://api.cognitive.microsoft.com/bing/v7.0/search

to

    https://api.bing.microsoft.com/v7.0/search

according to [this "How-to guide" from Microsoft](https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/bing-web-upgrade-guide-v5-to-v7).

I currently do not have an API key to test the change; so— hope it works for you.

**Comment by ghost** [comment]
@buddydvd i ended up hacking a solution with puppeteer after this failed. my question is, does this cli get the image link for the final raw full size image or only the smaller size image displayed in the initial search result? if the answer is former i will retry cli.

**Comment by buddydvd** [comment]
@planetrenox The response JSON object includes the `contentUrl` field (which points to the original image URL). I've included a sample output in this repository's `README.md` file. Refer to the official [Bing Image Search API documentation](https://learn.microsoft.com/en-us/bing/search-apis/bing-image-search/reference/response-objects) for more detail.

You can also check out [bing-image-search-async-iterator](https://github.com/funpokes/bing-image-search-async-iterator)  for a library version of this CLI tool.
